[workspace]
members = [
    "pgs/pgs",
    "pgs/pgs-std",
    "pgs/pgs-derive",
    "pglex/pglex",
    "pglex/pglex-derive",
    "pgsh"
]

[profile.release]
opt-level = 3
debug = false
incremental = true
lto = true

[profile.test]
debug = true